import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { IconDownload, IconPrinter, IconCheck } from "@tabler/icons-react";

interface DigitalReceiptProps {
  orderId: string;
  farmerName: string;
  buyerName: string;
  buyerPhone: string;
  variety: string;
  qualityGrade: string;
  quantity: number;
  pricePerKg: number;
  totalAmount: number;
  deliveryLocation: string;
  deliveryDate: string;
  transactionId?: string;
  paymentMethod?: string;
  onDownload?: () => void;
  onPrint?: () => void;
}

export function DigitalReceipt({
  orderId,
  farmerName,
  buyerName,
  buyerPhone,
  variety,
  qualityGrade,
  quantity,
  pricePerKg,
  totalAmount,
  deliveryLocation,
  deliveryDate,
  transactionId,
  paymentMethod = "M-PESA",
  onDownload,
  onPrint,
}: DigitalReceiptProps) {
  const handleDownload = () => {
    if (onDownload) {
      onDownload();
      return;
    }
    // Default download implementation
    const receiptContent = generateReceiptHTML();
    const blob = new Blob([receiptContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `receipt-${orderId}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    if (onPrint) {
      onPrint();
      return;
    }
    // Default print implementation
    window.print();
  };

  const generateReceiptHTML = () => {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>Receipt - ${orderId}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: 0 auto; }
    .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 20px; }
    .section { margin: 20px 0; }
    .row { display: flex; justify-content: space-between; margin: 10px 0; }
    .total { font-size: 18px; font-weight: bold; border-top: 2px solid #000; padding-top: 10px; margin-top: 20px; }
    .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="header">
    <h1>OFSP Digital Marketplace</h1>
    <h2>Digital Receipt</h2>
    <p>Order ID: ${orderId}</p>
    <p>Date: ${new Date(deliveryDate).toLocaleDateString("en-KE")}</p>
  </div>
  <div class="section">
    <h3>Transaction Details</h3>
    <div class="row"><span>Transaction ID:</span><span>${transactionId || "N/A"}</span></div>
    <div class="row"><span>Payment Method:</span><span>${paymentMethod}</span></div>
  </div>
  <div class="section">
    <h3>Farmer Information</h3>
    <div class="row"><span>Name:</span><span>${farmerName}</span></div>
  </div>
  <div class="section">
    <h3>Buyer Information</h3>
    <div class="row"><span>Name:</span><span>${buyerName}</span></div>
    <div class="row"><span>Phone:</span><span>${buyerPhone}</span></div>
  </div>
  <div class="section">
    <h3>Order Details</h3>
    <div class="row"><span>Variety:</span><span>${variety}</span></div>
    <div class="row"><span>Quality Grade:</span><span>Grade ${qualityGrade}</span></div>
    <div class="row"><span>Quantity:</span><span>${quantity} kg</span></div>
    <div class="row"><span>Price per kg:</span><span>KES ${pricePerKg}</span></div>
    <div class="row"><span>Delivery Location:</span><span>${deliveryLocation}</span></div>
    <div class="row"><span>Delivery Date:</span><span>${new Date(deliveryDate).toLocaleDateString("en-KE")}</span></div>
  </div>
  <div class="total">
    <div class="row"><span>Total Amount:</span><span>KES ${totalAmount.toLocaleString()}</span></div>
  </div>
  <div class="footer">
    <p>This is a digital receipt generated by the OFSP Digital Marketplace Platform</p>
    <p>For inquiries, contact support</p>
  </div>
</body>
</html>
    `;
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <IconCheck className="h-5 w-5 text-green-500" />
            Digital Receipt
          </CardTitle>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" onClick={handleDownload}>
              <IconDownload className="h-4 w-4 mr-2" />
              Download
            </Button>
            <Button size="sm" variant="outline" onClick={handlePrint}>
              <IconPrinter className="h-4 w-4 mr-2" />
              Print
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          {/* Header */}
          <div className="text-center border-b pb-4">
            <h2 className="text-2xl font-bold">OFSP Digital Marketplace</h2>
            <p className="text-muted-foreground">Digital Receipt</p>
            <div className="mt-2 space-y-1">
              <p className="font-medium">Order ID: {orderId}</p>
              <p className="text-sm text-muted-foreground">
                Date: {new Date(deliveryDate).toLocaleDateString("en-KE", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </p>
            </div>
          </div>

          {/* Transaction Details */}
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Transaction Details</h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-muted-foreground">Transaction ID:</span>
              <span className="font-medium">{transactionId || "N/A"}</span>
              <span className="text-muted-foreground">Payment Method:</span>
              <span className="font-medium">{paymentMethod}</span>
            </div>
          </div>

          {/* Farmer Information */}
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Farmer Information</h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-muted-foreground">Name:</span>
              <span className="font-medium">{farmerName}</span>
            </div>
          </div>

          {/* Buyer Information */}
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Buyer Information</h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-muted-foreground">Name:</span>
              <span className="font-medium">{buyerName}</span>
              <span className="text-muted-foreground">Phone:</span>
              <span className="font-medium">{buyerPhone}</span>
            </div>
          </div>

          {/* Order Details */}
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Order Details</h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-muted-foreground">Variety:</span>
              <span className="font-medium">{variety}</span>
              <span className="text-muted-foreground">Quality Grade:</span>
              <Badge variant="outline">Grade {qualityGrade}</Badge>
              <span className="text-muted-foreground">Quantity:</span>
              <span className="font-medium">{quantity} kg</span>
              <span className="text-muted-foreground">Price per kg:</span>
              <span className="font-medium">KES {pricePerKg}</span>
              <span className="text-muted-foreground">Delivery Location:</span>
              <span className="font-medium">{deliveryLocation}</span>
              <span className="text-muted-foreground">Delivery Date:</span>
              <span className="font-medium">
                {new Date(deliveryDate).toLocaleDateString("en-KE", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </span>
            </div>
          </div>

          {/* Total */}
          <div className="border-t pt-4">
            <div className="flex justify-between items-center">
              <span className="text-lg font-semibold">Total Amount:</span>
              <span className="text-2xl font-bold">KES {totalAmount.toLocaleString()}</span>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center text-xs text-muted-foreground pt-4 border-t">
            <p>This is a digital receipt generated by the OFSP Digital Marketplace Platform</p>
            <p className="mt-1">For inquiries, contact support</p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

